### ISSUE TITLE
Animate keeps keeps firing

### ISSUE THREAD

**Issue by jameswlane** [matthieua/WOW#151]
I am adding WOW.js and Animate.css to a site I been working on. But I ran into what may be a bug. WOW keeps firing and adding animate to the element for every time I scroll. That seems like a very unwanted. Could you please give me some advice how I can get it to only fire once on a element.

Here is a video of the site and source.

https://www.dropbox.com/s/6qhjo1nd9wtdril/screencast_2015-01-23_00-09-52_0_edited_0_edited.mp4?dl=0

**Comment by mdeboer** [comment]
It is hard to tel by your video what's going on but I guess it's caused by another script in your page that forces a complete reflow, I would recommend trying to replicate the bug in a smaller environment (jsfiddle / codepen). If you're more of a debugger you can try to trace every event that's triggered when scrolling and see what's causing it by setting breakpoints. If you got access to the theme files try disabling scripts one by one to see which is the culprit.

**Comment by ishan-marikar** [comment]
Hi, I've been having the same happen to me. All the scroll events keep firing repeatedly.
All I have in my scripts are 
``` js
var jQuery = require('jquery');
if (!window.jQuery) {
  window.$ = window.jQuery = jQuery;
}
new WOW().init();
```
